### ISSUE TITLE
Comparison with other libraries

### ISSUE THREAD

**Issue by seandenigris** [SquareBracketAssociates/Booklet-Smacc#13]
The conclusion briefly mentions PetitParser, but it would be nice to have a more thorough comparison. There are now several St parsing libraries (e.g. Xtreams, PP) and the tradeoffs do not seem at all clear...

# Possibilities
- Fewer Dependencies - the runtime package seems to be the only requirement, which itself has no additional requirements.

# Questions
- With PP2 optimizations, is it still a universal truth that SmaCC is faster to a meaningful degree? I saw some benchmarks showing a significant PP speedup after optimization, but can't remember where...

**Comment by Ducasse** [comment]
I agree but I do not have the time nor energy to do it because I'm alone here.

**Comment by seandenigris** [comment]
Thanks for letting me know. I get it!
